package org.example.LogInSystem;

public class ExceptionClassInJava extends Throwable {
/* monday's class
    public static void main(String[] args) throws Exception {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter a number: ");
        int num = scanner.nextInt();

        System.out.print("Enter a Second number: ");
        int num2 = scanner.nextInt();
        System.out.println(num+num2);
    }
*/

  /* first class work

  public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        try{
            System.out.print("Enter a number ");
            int num = scanner.nextInt();
            System.out.print("Enter another number ");
            int num2 = scanner.nextInt();
            System.out.println(num + num2);
            System.out.println("The addition is " + (num + num2));
            System.out.println("Input num 3");
            int num3 = scanner.nextInt();
            System.out.println("The addition is " + ((num + num2) /num3));
        }
        catch (NumberFormatException e){
            System.out.println("Wrong arithmetic operation");
            main(args);
        }
        catch (InputMismatchException e){
            System.out.println("Input a number ode");
            main(args);
        }
    }
*/

    public static void main(String[] args) {

    }
}
                                           